# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce8b3f152a8e2c0612b850615cbd65d3e873d3162ea5431279cba0d0b8b099c0be441cd8876ecd58fa73c9358726b3473c0437c1d93589032a124785322e01f

test:
  secret_key_base: 7cdc59ee9df0c95b6beef79718b77ef31efa0c13c1c13a8e07be47a0eeb1b78ca56060a6475eb57a4685879c4a242724c0f04a586523a6d1e4d753baaa35f8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
