# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4e10b955adbc1fe8cf4df7242b15f38e4757457f6d3e410804473c8e24ed8a31ffdc38e1616e8f2b8f5ab125162896ce42c7fc5b9c675adbddccf657a5118da

test:
  secret_key_base: c0089bec56ca0095932f9b93eee4bb9e894efc1b5e52aa9ef505bbb9c5a5857896aeabd2a2aed4d29bbef7cb69c695e1cd67bae9a11998b17abad6abc03447eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
